marketing_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5434
      user: marketinguser
      password: marketingpass
      dbname: marketingdb_destination
      schema: raw
      threads: 4
