marketing_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'postgres-dest') }}"
      port: "{{ env_var('DBT_PORT', '5432') | int }}"
      user: marketinguser
      password: marketingpass
      dbname: marketingdb_destination
      schema: raw
      threads: 4
